services:
  shelv:
    image: ghcr.io/gatzenga/shelv-web:latest
    container_name: shelv
    restart: unless-stopped
    user: 1037:100
    environment:
      - NAVIDROME_URL=http://172.168.22.10:4533
      - LYRICS_SERVER=https://lrclib.vkugler.ch
      - LANGUAGE=en
      - SIDEBAR_ARTISTS=true
      - SIDEBAR_SONGS=true
      - SIDEBAR_ALBUMS=true
      - SIDEBAR_GENRES=false
      - SIDEBAR_RADIOS=true
      - FEATURE_FAVORITES=false
      - FEATURE_PLAYLISTS=false
      - CACHE_IMAGES=true
      - CACHE_LYRICS=true
      - LASTFM_API=
      - LASTFM_SECRET=
      - LASTFM_TOP_SONGS=false
      - LASTFM_MIXES=true
      - SONGS_TO_ADD=5
      - MATCH_CURRENT_SONG=true
    volumes:
      - /volume2/docker/shelv/cache:/cache
      - /volume2/docker/shelv/config/lastfm:/config/lastfm
      - /volume2/docker/shelv/logs:/logs
    ports:
      - "127.0.0.1:9180:8080"
    networks:
      navidrome:
        ipv4_address: 172.168.22.80

networks:
  navidrome:
    external: true
