services:
  shelv:
    image: ghcr.io/gatzenga/shelv-web:latest
    container_name: shelv
    restart: unless-stopped
    user: UID:GID
    environment:
      - NAVIDROME_URL=http://NAVIDROME_HOST:4533
      - INCLUDE_NAVIDROME_LYRICS=true
      # - LYRICS_CUSTOM_SERVER=https://custom-lrclib.org
      - LRCLIB_FALLBACK=true
      - LANGUAGE=en
      - SIDEBAR_ARTISTS=true
      - SIDEBAR_ALBUMS=true
      - SIDEBAR_GENRES=true
      - SIDEBAR_RADIOS=true
      - FEATURE_FAVORITES=true
      - FEATURE_PLAYLISTS=true
      - CACHE_IMAGES=true
      - CACHE_LYRICS=true
      - LASTFM_API=YOUR_LASTFM_API_KEY
      - LASTFM_SECRET=YOUR_LASTFM_SECRET
      - LASTFM_TOP_SONGS=true
      - LASTFM_MIXES=true
      - DISCOVER_SECTIONS=smart-mixes,recently-added,recently-played,frequently-played,random-albums
      - SONGS_TO_ADD=5
      - MATCH_CURRENT_SONG=true
    volumes:
      - /path/to/shelv/cache:/cache
      - /path/to/shelv/config:/config
      - /path/to/shelv/logs:/logs
    ports:
      - "127.0.0.1:9180:8080"
    networks:
      YOUR_NETWORK:
        ipv4_address: YOUR_CONTAINER_IP

networks:
  YOUR_NETWORK:
    external: true
