overrides:
  brace-expansion: ^2.0.2
  glob: ^11.0.0
  tar: ^7.5.7
  "minimatch@10": "^10.2.3"
  postcss: ^8.5.23
  "nanoid@3": ^3.3.18
  "picomatch@2": ^2.3.2
  yaml: ^2.8.3
  "postcss-selector-parser@6": ^6.1.3

blockExoticSubdeps: false

allowBuilds:
  bufferutil: set this to true or false
  esbuild: true
  utf-8-validate: set this to true or false
